// src/components/common/episode-card.tsx
import Button from '$components/ui/button';
import Image from '$components/ui/image';
import Icon from '$components/ui/icon';
import LiveSign from './live-sign';
import { playerDetail } from '$lib/stores/player';
import type { AlternativeEnclosure } from '$lib/types';
import { getTime } from '$lib/utils/time';
import { Match, mergeProps, Show, splitProps, Switch } from 'solid-js';
import s from './episode-card.module.css';

interface EpisodeCardProps {
	type?: 'podcast' | 'live';
	feed: string;
	feedId: string;
	title: string;
	image: string;
	summary?: string;
	explicit?: boolean;
	guid: string;
	enclosure: string;
	altEnclosure?: AlternativeEnclosure[];
	// podcast
	episode?: number;
	publishedDate?: string;
	duration?: number;
	// live
	status?: 'live' | 'ended' | 'pending';
	start?: string;
	end?: string;
	// linked to feed
	linked?: boolean;
}

const LiveDateTime = (props: Pick<EpisodeCardProps, 'status' | 'start' | 'end'>) => {
	return (
		<>
			<Show when={props.status === 'live'}>
				<LiveSign />
			</Show>
			<span>
				<Switch>
					<Match when={props.status === 'live' && props.end}>
						end {getTime(props.end ? props.end : 0)}
					</Match>
					<Match when={props.status === 'pending' && props.start}>
						started {getTime(props.start ? props.start : 0)}
					</Match>
					<Match when={props.status === 'ended' && props.end}>
						ended {getTime(props.end ? props.end : 0)}
					</Match>
				</Switch>
			</span>
		</>
	);
};

const LiveTitle = (props: Pick<EpisodeCardProps, 'linked' | 'feedId' | 'title' | 'feed'>) => {
	return (
		<>
			<Show when={props.linked}>
				<a href={`/podcast/${props.feedId}`} class={`${s.title} ${s.link} ${s.linked} text-sm`}>
					<span>{props.feed}</span>
				</a>
			</Show>
			<h3>
				<span>{props.title}</span>
			</h3>
		</>
	);
};

const PodcastDateTime = (
	props: Pick<EpisodeCardProps, 'duration' | 'publishedDate' | 'episode'>
) => {
	const duration = props.duration ? props.duration : 0;
	return (
		<>
			<Show when={props.episode}>
				<span>Eps {props.episode}</span>
			</Show>
			<span>{getTime(props.publishedDate ? props.publishedDate : 0)}</span>
			<span>{Math.floor(duration / 60)} min</span>
		</>
	);
};

const PodcastTitle = (props: Pick<EpisodeCardProps, 'feedId' | 'guid' | 'title'>) => {
	return (
		<h3 class={s.title}>
			<a class={s.link} href={`/podcast/${props.feedId}/${btoa(encodeURI(props.guid))}`}>
				<span>{props.title}</span>
			</a>
		</h3>
	);
};

export default function EpisodeCard(props: EpisodeCardProps) {
	const { setPlayNow, playNow, paused, setPaused, loading } = playerDetail();
	const mergedProps = mergeProps(
		{
			type: 'podcast'
		},
		props
	);
	const [feed, live, podcast] = splitProps(
		mergedProps,
		['feed', 'feedId'],
		['end', 'start', 'status', 'linked']
	);
	const buttonPlay = () => {
		setPlayNow({
			feed: {
				id: feed.feedId,
				title: feed.feed
			},
			podcast: {
				title: podcast.title,
				image: podcast.image,
				enclosure: podcast.enclosure,
				guid: podcast.guid,
				altEnclosure: podcast.altEnclosure
			}
		});

		if (playNow().podcast.enclosure === podcast.enclosure) {
			setPaused(!paused());
		}
	};

	return (
		<div class={s['episode-card']}>
			<div class={s.img}>
				<Image src={podcast.image} alt={`${podcast.title} by ${feed.feed}`} full />
			</div>
			<div class={s.content}>
				<div
					class={`${s.time} text-sm`}
					classList={{ 'list-with-dot': podcast.type === 'podcast' }}
				>
					<Switch>
						<Match when={podcast.type === 'podcast'}>
							<PodcastDateTime {...podcast} />
						</Match>
						<Match when={podcast.type === 'live'}>
							<LiveDateTime {...live} />
						</Match>
					</Switch>
					<Show when={podcast.explicit}>
						<Icon name="explicit" size={18} />
					</Show>
				</div>
				<Switch>
					<Match when={podcast.type === 'podcast'}>
						<PodcastTitle title={podcast.title} guid={podcast.guid} feedId={feed.feedId} />
					</Match>
					<Match when={podcast.type === 'live'}>
						<LiveTitle
							linked={live.linked}
							title={podcast.title}
							feed={feed.feed}
							feedId={feed.feedId}
						/>
					</Match>
				</Switch>
				<Show when={podcast.summary}>
					<div class={`${s.summary} text-sm`} innerHTML={podcast.summary} />
				</Show>
			</div>

			<Button
				aria-label="Play podcast"
				icon={playNow().podcast.enclosure === podcast.enclosure && !paused() ? 'pause' : 'play'}
				aria-pressed={playNow().podcast.enclosure === podcast.enclosure && !paused()}
				variant="picton"
				class={s.play}
				onClick={buttonPlay}
				loading={playNow().podcast.enclosure === podcast.enclosure && loading()}
			/>
		</div>
	);
}

// src/lib/components/common/EpisodeCard.svelte
<script lang="ts">
	import { Button, Icon, Image, LiveSign } from '$lib/components';
	import { getTime } from '$lib/utils/time';
	import { playerDetail } from '$lib/stores/player.svelte';
	import type { AlternativeEnclosure } from '$lib/types';

	interface EpisodeCardProps {
		type?: 'podcast' | 'live';
		feed: string;
		feedId: string;
		title: string;
		image: string;
		summary?: string;
		explicit?: boolean;
		guid: string;
		enclosure: string;
		altEnclosure?: AlternativeEnclosure[];
		// podcast
		episode?: number;
		publishedDate?: string;
		duration?: number;
		// live
		status?: 'live' | 'ended' | 'pending';
		start?: string;
		end?: string;
		// linked to feed
		linked?: boolean;
	}

	let {
		type = 'podcast',
		feed,
		feedId,
		title,
		summary,
		image,
		publishedDate: date,
		duration,
		explicit,
		guid,
		enclosure,
		altEnclosure,
		episode,
		status,
		start,
		end,
		linked
	}: EpisodeCardProps = $props();

	const playState = playerDetail();

	const buttonPlay = () => {
		playState.feed = {
			id: feedId,
			title: feed
		};
		playState.podcast = {
			title,
			image,
			enclosure: enclosure,
			explicit,
			guid,
			altEnclosure
		};
		if (playState.podcast.enclosure === enclosure) {
			playState.paused = !playState.paused;
		}
	};
</script>

{#snippet liveDateTime()}
	{#if status === 'live'}
		<span>
			<LiveSign />
		</span>
	{/if}
	<span>
		{#if status === 'live' && end}
			ended {getTime(end)}
		{/if}
		{#if status === 'pending' && start}
			start {getTime(start)}
		{/if}
		{#if status === 'ended' && end}
			ended {getTime(end)}
		{/if}
	</span>
{/snippet}

{#snippet liveTitle()}
	{#if linked}
		<a class="title linked text-sm" href={`/podcast/${feedId}`}>
			<span>
				{feed}
			</span>
		</a>
	{/if}
	<h3 class="title">
		<span>
			{title}
		</span>
	</h3>
{/snippet}

{#snippet podcastTitle()}
	<h3 class="title">
		<a href={`/podcast/${feedId}/${btoa(encodeURI(guid))}`}>
			<span>
				{title}
			</span>
		</a>
	</h3>
{/snippet}

{#snippet podcastDateTime()}
	{#if date && duration}
		{#if episode}
			<span>
				Episode {episode}
			</span>
		{/if}
		<span>
			{getTime(date)}
		</span>
		<span class="duration-span">{Math.floor(duration / 60)} min</span>
	{/if}
{/snippet}

<div class="episode-card card">
	<div class="img">
		<Image src={image} alt={`${title} by ${feed}`} full />
	</div>
	<div class="content">
		<div class:list-with-dot={type === 'podcast'} class="time text-sm">
			{#if type === 'live'}
				{@render liveDateTime()}
			{:else}
				{@render podcastDateTime()}
			{/if}
			{#if explicit}
				<Icon name="explicit" stroke="none" size={18} class="explicit" />
			{/if}
		</div>
		{#if type === 'live'}
			{@render liveTitle()}
		{:else}
			{@render podcastTitle()}
		{/if}
		{#if summary}
			<div class="summary text-sm">
				{@html summary}
			</div>
		{/if}
	</div>

	<Button
		type="button"
		aria-label="Play this episode"
		icon={playState.podcast.enclosure === enclosure && !playState.paused ? 'pause' : 'play'}
		variant="picton"
		class="play"
		onclick={buttonPlay}
	/>
</div>

<style>
	.episode-card {
		display: grid;
		grid-template-columns: auto minmax(0, 1fr) auto;
		align-items: center;
		width: 100%;
		border: 2px solid hsl(var(--pl-accent-95));
		border-radius: var(--pl-border-radius-sm);
		padding-inline: 0.5rem;
		padding-block: 0.25rem;
		gap: 0.5rem;
		transition-property: transform, box-shadow;
		transition-duration: 150ms;
		transition-timing-function: ease-in-out;

		@media (min-width: 768px) {
			padding-inline: 1rem;
			padding-block: 0.75rem;
			gap: 1rem;
		}

		&:hover {
			box-shadow: var(--pl-shadow-drop);
			transform: translate(-0.25rem, -0.25rem);
		}
	}

	.img {
		position: relative;
		display: block;
		border-radius: var(--pl-border-radius-sm);
		border: 2px solid hsl(var(--pl-accent-95));
		width: 100px;
		height: 100px;

		@media (max-width: 768px) {
			width: 50px;
			height: 50px;
		}
	}

	.content {
		display: flex;
		flex-direction: column;

		@media (min-width: 768px) {
			margin-inline-end: 1rem;
		}
	}
	.title {
		overflow: hidden;
		display: -webkit-box;
		-webkit-box-orient: vertical;
		-webkit-line-clamp: 2;
		line-clamp: 2;
	}

	.summary {
		color: hsl(var(--pl-accent-80));
		overflow: hidden;
		display: -webkit-box;
		-webkit-box-orient: vertical;
		-webkit-line-clamp: 3;
		line-clamp: 3;

		@media (max-width: 768px) {
			display: none;
		}
	}

	.time {
		font-weight: 500;
		display: inline-flex;
		flex-direction: row;
		align-items: center;

		&:has([data-is-live]) {
			gap: 0.25rem;
		}
	}

	.linked {
		font-weight: 500;
	}

	a:hover > span {
		box-shadow: var(--pl-shadow-highlight);
	}
</style>
