// src/components/layout/player.tsx
import RunningText from '$components/common/running-text';
import Button from '$components/ui/button';
import Image from '$components/ui/image';
import Progress from '$components/ui/progress';
import Slider from '$components/ui/slider';
import Icon from '$components/ui/icon';
import { playerDetail } from '$lib/stores/player';
import { useUI } from '$lib/stores/ui';
import { formatTime } from '$lib/utils/time';
import { For, Match, Show, Switch, createEffect, createMemo, createSignal } from 'solid-js';
import LiveSign from '$components/common/live-sign';
import { getWindowSize } from '$lib/utils/helper';
import s from './player.module.css';

export default function Player() {
	const {
		setCurrentTime,
		setDuration,
		setLoading,
		setPaused,
		playNow,
		currentTime,
		paused,
		loading,
		duration
	} = playerDetail();
	const uiState = useUI();
	const [loadStart, setLoadStart] = createSignal(true);
	const [fullPlayerOpen, setFullPlayerOpen] = createSignal(false);
	const [volume, setVolume] = createSignal(1);
	const [windowSize] = getWindowSize();

	let audio!: HTMLAudioElement;

	let playerFull!: HTMLDialogElement;

	const playerReady = createMemo(() => playNow().feed.id !== '');

	createEffect(() => {
		if (playerReady()) {
			if (paused()) {
				audio.pause();
			} else {
				audio.play();
			}
		}
	});

	const fullPlayerState = {
		open: () => {
			if (!playerFull) return;
			playerFull.showModal();
			setFullPlayerOpen(true);
		},
		close: () => {
			if (!playerFull) return;
			playerFull.close();
			setFullPlayerOpen(false);
		}
	};

	return (
		<Show when={playerReady()}>
			<div class={s.player} inert={uiState.menuOpen()}>
				<audio
					ref={audio}
					src={playNow().podcast.enclosure}
					preload="metadata"
					onloadstart={() => {
						setCurrentTime(0);
						setLoadStart(true);
						setLoading(true);
						navigator.mediaSession.metadata = new MediaMetadata({
							title: playNow().podcast.title,
							artist: playNow().feed.title,
							artwork: [
								{
									src: playNow().podcast.image
								}
							]
						});
					}}
					ondurationchange={() => {
						setDuration(Math.round(audio.duration));
					}}
					onloadeddata={() => {
						setPaused(false);
						setLoadStart(false);
					}}
					oncanplaythrough={() => {
						setLoading(false);
						audio.play();
					}}
					ontimeupdate={() => {
						setCurrentTime(Math.trunc(audio.currentTime));
					}}
					onseeking={() => {
						setLoadStart(false);
						setLoading(true);
					}}
					onended={() => {
						setPaused(true);
						setCurrentTime(0);
					}}
				>
					<Show when={playNow().podcast.altEnclosure}>
						<For each={playNow().podcast.altEnclosure}>
							{(item) => (
								<Switch>
									<Match when={item.default}>
										<source src={item.source[0].uri} type={item.type} />
									</Match>
									<Match when={!item.default}>
										<source src={item.source[0].uri} type={item.type} />
									</Match>
								</Switch>
							)}
						</For>
					</Show>
				</audio>

				<div class={s.seeker}>
					<Show
						when={Number.isFinite(duration()) && windowSize() > 1024}
						fallback={<Progress value={currentTime()} max={Math.round(duration())} />}
					>
						<Slider
							id="player-seeker"
							value={currentTime()}
							max={Math.round(duration())}
							onInput={(e) => {
								setCurrentTime(Number(e.target.value));
								audio.currentTime = currentTime();
							}}
						/>
					</Show>
				</div>
				<div class={s.wrapper}>
					<div class={s.controls}>
						<span class={s.backward}>
							<Button
								type="button"
								aria-label="skip 10 second backward"
								icon="skip-backward"
								onClick={() => {
									audio.currentTime = currentTime() - 10;
								}}
							/>
						</span>
						<span class={s.play}>
							<Button
								variant="picton"
								type="button"
								aria-label="Play podcast"
								aria-pressed={!paused()}
								loading={loading()}
								icon={paused() ? 'play' : 'pause'}
								onClick={() => setPaused(!paused())}
							/>
						</span>
						<span class={s.forward}>
							<Button
								type="button"
								aria-label="skip 10 second forward"
								icon="skip-forward"
								onClick={() => {
									audio.currentTime = currentTime() + 10;
								}}
							/>
						</span>
					</div>
					<div class={`${s.duration} text-sm`}>
						<Switch>
							<Match when={loadStart() && loading()}>
								<span>--/--</span>
							</Match>
							<Match when={!Number.isFinite(duration())}>
								<span class={s['live-sign']}>
									<LiveSign />
									<span>Live</span>
								</span>
							</Match>
							<Match when={!loadStart()}>
								<span>{formatTime(currentTime())}</span>
								<span>/</span>
								<span>{formatTime(duration())}</span>
							</Match>
						</Switch>
					</div>
					<div class={s.info}>
						<div class={s.thumbnail}>
							<Image src={playNow().podcast.image} alt={playNow().podcast.title} full />
						</div>
						<div class={`${s.title} text-sm`}>
							<div class={s.running}>
								<RunningText title={playNow().podcast.title} marginBottom="0.25rem">
									{playNow().podcast.title}
								</RunningText>
							</div>
							<a href={`/podcast/${playNow().feed.id}`} class={s.feed}>
								<span>{playNow().feed.title}</span>
							</a>
						</div>
					</div>
					<div class={s.full}>
						<Button
							type="button"
							variant="picton"
							aria-label="open full player"
							icon="chevron-up"
							aria-expanded={fullPlayerOpen()}
							onClick={fullPlayerState.open}
						/>
					</div>
				</div>
				<dialog ref={playerFull} class={s['player-modal']}>
					<Show when={fullPlayerOpen()}>
						<div class={s['player-modal-wrapper']}>
							<div class={s['player-modal-img']}>
								<Image src={playNow().podcast.image} alt={playNow().podcast.title} full />
							</div>

							<div class={s['player-modal-detail']}>
								<div class="text-lg">
									<RunningText textAlign="center">{playNow().podcast.title}</RunningText>
								</div>
								<div class={s['player-modal-feed-title']}>{playNow().feed.title}</div>
							</div>
							<div class={s['player-modal-controls']}>
								<div class={`${s['player-modal-seeker']} text-sm`}>
									<Show
										when={Number.isFinite(duration())}
										fallback={
											<span class={s['live-sign']}>
												<LiveSign />
												<span data-full-player>Live</span>
											</span>
										}
									>
										<Slider
											id="seeker-full-player"
											value={currentTime()}
											min={0}
											max={duration()}
											onInput={(e) => {
												setCurrentTime(Number(e.target.value));
												audio.currentTime = currentTime();
											}}
										/>
										<div>{formatTime(currentTime())}</div>
										<div>{formatTime(duration())}</div>
									</Show>
								</div>
								<div class={s['player-modal-control']}>
									<Button
										type="button"
										size="lg"
										aria-label="skip 10 second backward"
										icon="skip-backward"
										onClick={() => {
											audio.currentTime = currentTime() - 10;
										}}
									/>
									<Button
										type="button"
										size="lg"
										variant="picton"
										aria-label="Play podcast"
										aria-pressed={!paused()}
										loading={loading()}
										icon={paused() ? 'play' : 'pause'}
										onClick={() => setPaused(!paused())}
									/>
									<Button
										type="button"
										size="lg"
										aria-label="skip 10 second forward"
										icon="skip-forward"
										onClick={() => {
											audio.currentTime = currentTime() + 10;
										}}
									/>
								</div>
								<div class={s['player-modal-volume']}>
									<span>
										<Icon name="volume" />
									</span>
									<Slider
										id="volume"
										value={volume()}
										step={0.1}
										min={0}
										max={1}
										onInput={(e) => {
											setVolume(Number(e.target.value));
											audio.volume = volume();
										}}
									/>
									<span>
										<Icon name="volume-full" />
									</span>
								</div>
							</div>
							<Button
								type="button"
								size="full"
								aria-label="close full player"
								icon="close"
								onClick={fullPlayerState.close}
							/>
						</div>
					</Show>
				</dialog>
			</div>
		</Show>
	);
}

// src/lib/components/common/Player.svelte
<script lang="ts">
	import { Button, Image, Icons, Progress, Slider, useUI } from '$lib/components';
	import { playerState } from '$lib/stores/player.svelte';
	import RunningText from './RunningText.svelte';
	import { formatTime } from '$lib/utils/time';
	import { fly } from 'svelte/transition';

	const uiState = useUI();

	let podcast = $derived(playerState.podcast);
	let loadstart = $state(true);

	let current = $derived(Math.floor(playerState.currentTime));

	let windowWidth = $state(0);
</script>

<svelte:window bind:innerWidth={windowWidth} />

{#if uiState.player}
	<div transition:fly={{ y: 350, opacity: 1 }} class="player" inert={uiState.menuOpen}>
		{#key podcast.enclosure}
			<audio
				src={podcast.enclosure}
				preload="metadata"
				bind:duration={playerState.duration}
				bind:currentTime={playerState.currentTime}
				bind:paused={playerState.paused}
				onloadstart={() => {
					playerState.currentTime = 0;
					loadstart = true;
					playerState.loading = true;
					navigator.mediaSession.metadata = new MediaMetadata({
						title: playerState.podcast.title,
						artist: playerState.feed.title,
						artwork: [
							{
								src: playerState.podcast.image
							}
						]
					});
				}}
				onloadeddata={() => {
					playerState.paused = false;
				}}
				onseeking={() => {
					loadstart = false;
					playerState.loading = true;
				}}
				oncanplay={() => {
					playerState.loading = false;
				}}
				onended={() => {
					playerState.paused = true;
					playerState.currentTime = 0;
				}}
			>
				{#if podcast.altEnclosure}
					{#each podcast.altEnclosure as alt}
						{#if alt.default}
							<source src={alt.source[0].uri} type={alt.type} />
						{:else}
							<source src={alt.source[0].uri} type={alt.type} />
						{/if}
					{/each}
				{/if}
			</audio>
			<div class="inner container">
				<div class="left">
					<Button
						type="button"
						variant="picton"
						title={playerState.paused ? 'Play' : 'Pause'}
						loading={playerState.loading}
						onclick={() => (playerState.paused = !playerState.paused)}
					>
						{#if playerState.paused}
							<Icons icon="play" aria-hidden="true" />
						{:else}
							<Icons icon="pause" aria-hidden="true" />
						{/if}
					</Button>
					<div class="duration text-sm">
						{#if loadstart && playerState.loading}
							--/--
						{:else if !Number.isFinite(playerState.duration)}
							<span class="live-sign">
								<span class="sign">
									<span class="pulse"></span>
									<span></span>
								</span>
								<span>Live</span>
							</span>
						{:else}
							<span>{formatTime(current)}</span>
							<span>/</span>
							<span>{formatTime(playerState.duration)}</span>
						{/if}
					</div>
				</div>
				<div class="mid">
					<div class="thumbnail">
						<Image src={podcast.image} alt={podcast.title} full />
					</div>
					<div class="title">
						<RunningText class="text-normal">
							<span class:explicit={podcast.explicit}>
								{podcast.title}
							</span>
						</RunningText>
						<a href={`/podcast/${playerState.feed.id}`} class="text-sm">
							{playerState.feed.title}
						</a>
					</div>
				</div>
				<div class="right">another</div>
			</div>
			<div class="upper">
				{#if Number.isFinite(playerState.duration) && windowWidth > 1024}
					<Slider
						id="seeker"
						bind:now={playerState.currentTime}
						min={0}
						max={Math.floor(playerState.duration)}
						disabled={!Number.isFinite(playerState.duration)}
					/>
				{:else}
					<Progress
						min={0}
						max={Number.isFinite(playerState.duration) ? Math.floor(playerState.duration) : 1}
						now={Number.isFinite(playerState.duration) ? current : 1}
						label="Podcast progress"
					/>
				{/if}
			</div>
		{/key}
	</div>
{/if}

<style>
	.player {
		position: sticky;
		bottom: 0px;
		z-index: 10;
		display: block;
		width: 100%;
		background-color: var(--accent-5);
		height: var(--space-16);

		@media (min-width: 768px) {
			height: var(--space-20);
		}
	}

	.inner {
		margin-inline: auto;
		display: grid;
		width: 100%;
		height: 100%;
		grid-template-columns: repeat(8, minmax(0, 1fr));
		gap: var(--space-5);
		padding-block: var(--space-3);

		& > .left {
			grid-column: span 2 / span 2;
			display: none;

			@media (min-width: 768px) {
				display: flex;
				gap: var(--space-3);
				align-items: center;
			}

			.duration {
				display: flex;
				position: relative;
				gap: var(--space-1);
			}
		}

		& > .mid {
			grid-column: span 6 / span 6;
			display: flex;
			position: relative;
			width: 100%;
			align-items: center;
			column-gap: var(--space-2);

			@media (min-width: 768px) {
				grid-column: span 5 / span 5;
			}
			@media (min-width: 1024px) {
				column-gap: var(--space-3);
			}

			& > .thumbnail {
				display: block;
				position: relative;
				aspect-ratio: 1 / 1;
				width: var(--space-8);
				flex: none;
				overflow: hidden;
				border-radius: var(--space-2);
				border: 2px solid currentColor;

				@media (min-width: 768px) {
					width: var(--space-12);
				}
			}
			& > .title {
				display: flex;
				flex-direction: column;
				overflow: hidden;

				@media (min-width: 768px) {
					gap: var(--space-1);
				}

				& > a {
					max-width: fit-content;
					overflow: hidden;
					text-overflow: ellipsis;
					white-space: nowrap;
					text-transform: uppercase;
					color: var(--accent-80);

					&:hover {
						color: var(--picton);
					}
				}
			}
		}

		& > .right {
			grid-column: span 2 / span 2;
			width: 100%;

			@media (min-width: 768px) {
				grid-column: span 1 / span 1;
			}
		}
	}

	.upper {
		display: block;
		position: absolute;
		left: 0px;
		height: fit-content;
		width: 100%;
		top: 0px;

		&:has([role='slider']) {
			top: -0.375rem;
		}

		@media (min-width: 1024px) {
			display: flex;
			text-align: center;
		}
	}
</style>
