// src/lib/components/common/Truncate.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { untrack } from "svelte";
	import { Button } from "$lib/components";

	interface DescriptionProps extends HTMLAttributes<HTMLDivElement> {
		as?: string;
		children: Snippet;
		truncate?: number;
	}
	let {
		as = "span",
		children,
		truncate = 3,
		class: className,
		...attrs
	}: DescriptionProps = $props();

	let open = $state(false);
	let parentHeight = $state(0);
	let elementHeight = $state(1000);
	let isTruncate = $state(true);

	let element: HTMLElement | undefined = $state();

	$effect.pre(() => {
		if (!element) return;
		elementHeight = element.scrollHeight;
		untrack(() => {
			isTruncate = elementHeight > parentHeight;
		});
	});
</script>

<div
	class={["root", className]}
	bind:clientHeight={parentHeight}
	style:--pl-description-truncate={truncate}
	{...attrs}
>
	<svelte:element
		this={as}
		bind:this={element}
		data-open-more={open}
		class={["truncate", { mask: isTruncate }]}
	>
		{@render children()}
	</svelte:element>

	{#if isTruncate}
		<Button type="button" variant="text" size="full" onclick={() => (open = !open)}>
			{open ? "Show Less" : "Show More"}
		</Button>
	{/if}
</div>

<style>
	.root {
		display: block;
	}

	.truncate {
		overflow-wrap: break-word;

		&[data-open-more="false"] {
			overflow: hidden;
			display: -webkit-box;
			-webkit-box-orient: vertical;
			-webkit-line-clamp: var(--pl-description-truncate);
			line-clamp: var(--pl-description-truncate);
		}
	}
	.mask {
		&[data-open-more="false"] {
			mask-image: linear-gradient(
				to top,
				transparent 0%,
				hsla(var(--pl-accent-95)) 90%,
				transparent 100%
			);
		}
	}
</style>

// src/components/common/truncate.tsx
import Button from '$components/ui/button';
import { Show, createMemo, createSignal, onMount } from 'solid-js';
import type { JSXElement } from 'solid-js';
import s from './truncate.module.css';

interface TruncateProps {
	truncate?: number;
	children: JSXElement;
}

export default function Truncate(props: TruncateProps) {
	const [open, setOpen] = createSignal(false);
	const [scrollHeight, setScrollHeight] = createSignal(1000);
	const [parentHeight, setParentHeight] = createSignal(0);

	let rootElement!: HTMLDivElement;
	let element!: HTMLDivElement;

	onMount(() => {
		setScrollHeight(element.scrollHeight);
		setParentHeight(rootElement.getBoundingClientRect().height);
	});

	const isTruncate = createMemo(() => {
		if (parentHeight() === 0) return false;

		return scrollHeight() > parentHeight();
	});

	return (
		<div
			ref={rootElement}
			class={s.root}
			style={{ '--pl-description-truncate': props.truncate ?? 3 }}
		>
			<div
				ref={element}
				data-open-more={open()}
				class={s.truncate}
				classList={{ [s.mask]: isTruncate() }}
			>
				{props.children}
			</div>
			<Show when={isTruncate()}>
				<Button type="button" variant="text" size="full" onClick={() => setOpen(!open())}>
					{open() ? 'Show Less' : 'Show More'}
				</Button>
			</Show>
		</div>
	);
}
