// src/components/layout/player.tsx
import RunningText from '$components/common/running-text';
import Button from '$components/ui/button';
import Image from '$components/ui/image';
import Progress from '$components/ui/progress';
import Slider from '$components/ui/slider';
import Icon from '$components/ui/icon';
import { playerDetail } from '$lib/stores/player';
import { useUI } from '$lib/stores/ui';
import { formatTime } from '$lib/utils/time';
import { For, Match, Show, Switch, createEffect, createMemo, createSignal } from 'solid-js';
import LiveSign from '$components/common/live-sign';
import { getWindowSize } from '$lib/utils/helper';
import s from './player.module.css';

export default function Player() {
	const {
		setCurrentTime,
		setDuration,
		setLoading,
		setPaused,
		playNow,
		currentTime,
		paused,
		loading,
		duration
	} = playerDetail();
	const uiState = useUI();
	const [loadStart, setLoadStart] = createSignal(true);
	const [fullPlayerOpen, setFullPlayerOpen] = createSignal(false);
	const [volume, setVolume] = createSignal(1);
	const [windowSize] = getWindowSize();

	let audio!: HTMLAudioElement;

	let playerFull!: HTMLDialogElement;

	const playerReady = createMemo(() => playNow().feed.id !== '');

	createEffect(() => {
		if (playerReady()) {
			if (paused()) {
				audio.pause();
			} else {
				audio.play();
			}
		}
	});

	const fullPlayerState = {
		open: () => {
			if (!playerFull) return;
			playerFull.showModal();
			setFullPlayerOpen(true);
		},
		close: () => {
			if (!playerFull) return;
			playerFull.close();
			setFullPlayerOpen(false);
		}
	};

	return (
		<Show when={playerReady()}>
			<div class={s.player} inert={uiState.menuOpen()}>
				<audio
					ref={audio}
					src={playNow().podcast.enclosure}
					preload="metadata"
					onloadstart={() => {
						setCurrentTime(0);
						setLoadStart(true);
						setLoading(true);
						navigator.mediaSession.metadata = new MediaMetadata({
							title: playNow().podcast.title,
							artist: playNow().feed.title,
							artwork: [
								{
									src: playNow().podcast.image
								}
							]
						});
					}}
					ondurationchange={() => {
						setDuration(Math.round(audio.duration));
					}}
					onloadeddata={() => {
						setPaused(false);
						setLoadStart(false);
					}}
					oncanplaythrough={() => {
						setLoading(false);
						audio.play();
					}}
					ontimeupdate={() => {
						setCurrentTime(Math.trunc(audio.currentTime));
					}}
					onseeking={() => {
						setLoadStart(false);
						setLoading(true);
					}}
					onended={() => {
						setPaused(true);
						setCurrentTime(0);
					}}
				>
					<Show when={playNow().podcast.altEnclosure}>
						<For each={playNow().podcast.altEnclosure}>
							{(item) => (
								<Switch>
									<Match when={item.default}>
										<source src={item.source[0].uri} type={item.type} />
									</Match>
									<Match when={!item.default}>
										<source src={item.source[0].uri} type={item.type} />
									</Match>
								</Switch>
							)}
						</For>
					</Show>
				</audio>

				<div class={s.seeker}>
					<Show
						when={Number.isFinite(duration()) && windowSize() > 1024}
						fallback={<Progress value={currentTime()} max={Math.round(duration())} />}
					>
						<Slider
							id="player-seeker"
							value={currentTime()}
							max={Math.round(duration())}
							onInput={(e) => {
								setCurrentTime(Number(e.target.value));
								audio.currentTime = currentTime();
							}}
						/>
					</Show>
				</div>
				<div class={s.wrapper}>
					<div class={s.controls}>
						<span class={s.backward}>
							<Button
								type="button"
								aria-label="skip 10 second backward"
								icon="skip-backward"
								onClick={() => {
									audio.currentTime = currentTime() - 10;
								}}
							/>
						</span>
						<span class={s.play}>
							<Button
								variant="picton"
								type="button"
								aria-label="Play podcast"
								aria-pressed={!paused()}
								loading={loading()}
								icon={paused() ? 'play' : 'pause'}
								onClick={() => setPaused(!paused())}
							/>
						</span>
						<span class={s.forward}>
							<Button
								type="button"
								aria-label="skip 10 second forward"
								icon="skip-forward"
								onClick={() => {
									audio.currentTime = currentTime() + 10;
								}}
							/>
						</span>
					</div>
					<div class={`${s.duration} text-sm`}>
						<Switch>
							<Match when={loadStart() && loading()}>
								<span>--/--</span>
							</Match>
							<Match when={!Number.isFinite(duration())}>
								<span class={s['live-sign']}>
									<LiveSign />
									<span>Live</span>
								</span>
							</Match>
							<Match when={!loadStart()}>
								<span>{formatTime(currentTime())}</span>
								<span>/</span>
								<span>{formatTime(duration())}</span>
							</Match>
						</Switch>
					</div>
					<div class={s.info}>
						<div class={s.thumbnail}>
							<Image src={playNow().podcast.image} alt={playNow().podcast.title} full />
						</div>
						<div class={`${s.title} text-sm`}>
							<div class={s.running}>
								<RunningText title={playNow().podcast.title} marginBottom="0.25rem">
									{playNow().podcast.title}
								</RunningText>
							</div>
							<a href={`/podcast/${playNow().feed.id}`} class={s.feed}>
								<span>{playNow().feed.title}</span>
							</a>
						</div>
					</div>
					<div class={s.full}>
						<Button
							type="button"
							variant="picton"
							aria-label="open full player"
							icon="chevron-up"
							aria-expanded={fullPlayerOpen()}
							onClick={fullPlayerState.open}
						/>
					</div>
				</div>
				<dialog ref={playerFull} class={s['player-modal']}>
					<Show when={fullPlayerOpen()}>
						<div class={s['player-modal-wrapper']}>
							<div class={s['player-modal-img']}>
								<Image src={playNow().podcast.image} alt={playNow().podcast.title} full />
							</div>

							<div class={s['player-modal-detail']}>
								<div class="text-lg">
									<RunningText textAlign="center">{playNow().podcast.title}</RunningText>
								</div>
								<div class={s['player-modal-feed-title']}>{playNow().feed.title}</div>
							</div>
							<div class={s['player-modal-controls']}>
								<div class={`${s['player-modal-seeker']} text-sm`}>
									<Show
										when={Number.isFinite(duration())}
										fallback={
											<span class={s['live-sign']}>
												<LiveSign />
												<span data-full-player>Live</span>
											</span>
										}
									>
										<Slider
											id="seeker-full-player"
											value={currentTime()}
											min={0}
											max={duration()}
											onInput={(e) => {
												setCurrentTime(Number(e.target.value));
												audio.currentTime = currentTime();
											}}
										/>
										<div>{formatTime(currentTime())}</div>
										<div>{formatTime(duration())}</div>
									</Show>
								</div>
								<div class={s['player-modal-control']}>
									<Button
										type="button"
										size="lg"
										aria-label="skip 10 second backward"
										icon="skip-backward"
										onClick={() => {
											audio.currentTime = currentTime() - 10;
										}}
									/>
									<Button
										type="button"
										size="lg"
										variant="picton"
										aria-label="Play podcast"
										aria-pressed={!paused()}
										loading={loading()}
										icon={paused() ? 'play' : 'pause'}
										onClick={() => setPaused(!paused())}
									/>
									<Button
										type="button"
										size="lg"
										aria-label="skip 10 second forward"
										icon="skip-forward"
										onClick={() => {
											audio.currentTime = currentTime() + 10;
										}}
									/>
								</div>
								<div class={s['player-modal-volume']}>
									<span>
										<Icon name="volume" />
									</span>
									<Slider
										id="volume"
										value={volume()}
										step={0.1}
										min={0}
										max={1}
										onInput={(e) => {
											setVolume(Number(e.target.value));
											audio.volume = volume();
										}}
									/>
									<span>
										<Icon name="volume-full" />
									</span>
								</div>
							</div>
							<Button
								type="button"
								size="full"
								aria-label="close full player"
								icon="close"
								onClick={fullPlayerState.close}
							/>
						</div>
					</Show>
				</dialog>
			</div>
		</Show>
	);
}

// src/lib/components/player/Player.svelte
<script lang="ts">
	import { fly } from "svelte/transition";
	import { MediaQuery } from "svelte/reactivity";
	import { pushState } from "$app/navigation";
	import { page } from "$app/state";
	import { audiometadata } from "$lib/state/player.svelte";
	import { useUI } from "$lib/state/ui.svelte";
	import { formatTime } from "$lib/utils/time";
	import Button from "../Button.svelte";
	import Icon from "../Icon.svelte";
	import Image from "../Image.svelte";
	import Slider from "../Slider.svelte";
	import Livesign from "../Livesign.svelte";
	import RunningText from "../RunningText.svelte";
	import FullPlayer from "$lib/components/player/FullPlayer.svelte";

	let track = $derived(audiometadata.track);

	const largeScreen = new MediaQuery("min-width: 768px");

	let useSlider = $derived(largeScreen.current && Number.isFinite(audiometadata.duration));

	const openFullPlayer = () => {
		pushState("", {
			fullPlayer: true
		});
	};
</script>

<div class="player" transition:fly|global={{ y: 300, opacity: 1 }} inert={useUI.inert}>
	{#key track.enclosure}
		<div class="seeker">
			<Slider
				{useSlider}
				bind:value={audiometadata.currentTime}
				min={0}
				max={Number.isFinite(audiometadata.duration) && audiometadata.readyState > 0
					? audiometadata.duration
					: 1}
			/>
		</div>
		<div class="wrapper">
			<div class="controls">
				<span class="backward">
					<Button
						variant="theme"
						size="square"
						title="Backward 15 seconds"
						onclick={() => (audiometadata.currentTime = audiometadata.currentTime -= 15)}
					>
						<Icon name="skip-backward" isHidden />
						<span class="sr-only">skip 15 second backward</span>
					</Button>
				</span>
				<span>
					<Button
						size="square"
						title={audiometadata.paused ? "Play" : "Pause"}
						aria-pressed={!audiometadata.paused}
						onclick={() => (audiometadata.paused = !audiometadata.paused)}
					>
						{#if audiometadata.state === "loading"}
							<Icon name="spinner" isHidden class="animate-spin" />
						{:else if audiometadata.state === "play"}
							<Icon name="pause" isHidden />
						{:else}
							<Icon name="play" isHidden />
						{/if}
						<span class="sr-only">toggle play and pause</span>
					</Button>
				</span>
				<span class="forward">
					<Button
						variant="theme"
						size="square"
						title="Forward 15 seconds"
						onclick={() => (audiometadata.currentTime = audiometadata.currentTime += 15)}
					>
						<Icon name="skip-forward" isHidden />
						<span class="sr-only">skip 15 second forward</span>
					</Button>
				</span>
			</div>
			<div class="duration text-sm">
				{#if audiometadata.readyState === 0}
					<span>--:--</span>
					<span>/</span>
					<span>--:--</span>
				{:else if !Number.isFinite(audiometadata.duration)}
					<span>
						<Livesign />
						<span>Live</span>
					</span>
				{:else}
					<span>{formatTime(audiometadata.currentTime)}</span>
					<span>/</span>
					<span>{formatTime(audiometadata.duration)}</span>
				{/if}
			</div>
			<div class="metadata">
				<div class="thumbnail">
					<Image src={track.image} alt={track.title} full />
				</div>
				<div class="title text-sm">
					<div class="running">
						<RunningText>
							{track.title}
						</RunningText>
					</div>
					<a href={`/podcast/${track.feedId}`} class="feed">
						{#if track.explicit}
							<Icon
								name="explicit"
								aria-label="explicit content"
								class="explicit"
								stroke="none"
								size={18}
							/>
						{/if}
						<span>{track.feed}</span>
					</a>
				</div>
			</div>
			<div class="misc">
				<Button size="square" title="Full player" onclick={openFullPlayer}>
					<Icon name="chevron-up" isHidden />
					<span class="sr-only">open full player</span>
				</Button>
			</div>
		</div>
		<audio
			src={track.enclosure}
			preload="metadata"
			title={track.title}
			bind:duration={null, (v) => (audiometadata.duration = Math.round(v))}
			bind:currentTime={audiometadata.currentTime}
			bind:paused={audiometadata.paused}
			bind:volume={audiometadata.volume}
			bind:readyState={audiometadata.readyState}
			onloadstart={() => {
				audiometadata.currentTime = 0;
				navigator.mediaSession.metadata = new MediaMetadata({
					title: track.title,
					artist: track.feed,
					artwork: [
						{
							src: track.image
						}
					]
				});
			}}
			onloadeddata={() => {
				audiometadata.paused = false;
			}}
			onended={() => {
				audiometadata.paused = true;
				audiometadata.currentTime = 0;
			}}
		>
		</audio>
	{/key}
</div>

{#if page.state.fullPlayer}
	<FullPlayer />
{/if}

<style>
	.player {
		display: block;
		position: sticky;
		bottom: 0;
		background-color: var(--pl-accent-1);
		z-index: var(--pl-player-index);
		inline-size: 100%;
	}
	.wrapper {
		display: grid;
		grid-template-areas: "controls duration metadata misc";
		grid-template-columns: auto auto minmax(0, 1fr) auto;
		gap: calc(var(--pl-spacing) * 6);
		block-size: var(--pl-player-height);
		max-inline-size: 92dvw;
		margin-inline: auto;
		align-items: center;

		@media (max-width: 768px) {
			grid-template-areas: "metadata controls misc";
			grid-template-columns: minmax(0, 1fr) repeat(2, auto);
		}
	}

	.controls {
		grid-area: controls;
		display: flex;
		flex-direction: row;
		align-items: center;
		gap: calc(var(--pl-spacing) * 4);

		@media (max-width: 768px) {
			& > :where(.forward, .backward) {
				display: none;
			}
		}
	}
	.duration {
		grid-area: duration;
		display: grid;
		grid-auto-flow: column;
		grid-auto-columns: minmax(0, 1fr);
		align-items: center;
		justify-items: center;
		inline-size: 12ch;

		@media (max-width: 768px) {
			display: none;
		}
	}
	.metadata {
		grid-area: metadata;
		display: flex;
		flex-direction: row;
		gap: calc(var(--pl-spacing) * 4);
		inline-size: 100%;

		& > .thumbnail {
			display: block;
			position: relative;
			block-size: 2.5rem;
			inline-size: 2.5rem;
			overflow: hidden;
			border: solid 1px;
			border-radius: var(--pl-radius);
			flex-shrink: 0;

			@media (max-width: 768px) {
				block-size: 2.25rem;
				inline-size: 2.25rem;
			}
		}
		& > .title {
			display: flex;
			flex-direction: column;
			line-height: 1.2;
			justify-content: center;
			overflow: hidden;

			.feed {
				font-weight: 600;
				overflow: hidden;
				text-overflow: ellipsis;
				white-space: nowrap;

				&:hover span {
					box-shadow: var(--pl-shadow-highlight);
				}
			}
		}
	}
	.misc {
		grid-area: misc;
	}
</style>
